### ISSUE TITLE
Problem with lock feature

### ISSUE THREAD

**Issue by DKSM** [Xibalba/ZHorse#6]
Hello,

The horse is a little buggy when trying to take a horse locked.
Here is what happens when someone tries to take my horse, a kind of spam -> https://puu.sh/rhLwc/3263ffdb5b.png

The person trying to steal manages to pull the horse over a long distance and managed to break the rope (Spigot 1.10.2)

**Comment by Zedd7** [comment]
Hi,
Could you specify your ZHorse version ?

I had this issue myself, but in very rare occasions (no idea why for now). Is it the same for you ?
So what you can do (if you want) is trying the snapshot for version 1.6.0 available on [Spigot](https://www.spigotmc.org/threads/zhorse.45692/page-14#post-1911587)
I can't tell yet if it will fix it, but let's say that there is a 50% chance that it will, because 1.6.0 is focused on database and data (locked/shared/...) access.

**Comment by DKSM** [comment]
Hello, I use version 1.5.2
I tried version 1.6.0 and I get an error that appears in the console when I enter the command "/ zh lock" being on a horse

http://pastebin.com/ZAB5TKek

**Comment by Zedd7** [comment]
I fixed some of those issues today in snapshot 3, if your server has not been running on 1.6 for too long I suggest that you revert to 1.5.2 until 1.6.0 snapshot 3 is out.
At this moment we'll get back on the chat spam ;)

**Comment by Zedd7** [comment]
Snapshot 3 is out, so you can try it ;)

I went through your last error log (the one on pastebin) and could not find anything, except one thing, that is not related to database. So if you follow the steps on Spigot to set up 1.6.0 correctly, it should do fine :)

That one thing is the message "[ZHorse] A player is using an unavailable language : "null" !".
It's very clear that it should not happen as only one message is supposed to be sent and this could very well be related to the issue for which you opened this ticket. So I'll soon go through the execution process of /zh lock and see if I can manage to get spammed too.

If you can think of any detail (Java 8 ? PaperSpigot ? Particular chat plugins ?) relevant for this "investigation", please tell me !

**Comment by DKSM** [comment]
Here is an additional information:

Java 8: java version "1.8.0_101"
Spigot 1.10.2 : git-Spigot-570526c-758885
Plugins list: https://puu.sh/rlcoI/3e0693db6e.png

The only plugins that might influence the chat would essentialsXChat

Where can I download snapshot 3 ?

**Comment by Zedd7** [comment]
Here : https://www.spigotmc.org/threads/zhorse.45692/page-14#post-1919661

**Comment by DKSM** [comment]
It still does not work (The cat is always spam)

The console does not contain errors, it's clean

**Comment by Zedd7** [comment]
When I try to steal a **locked** horse of an **offline** player, I get the message twice, each time.
Does it also happen to you or does it show up more than 2 times per click ?

**Comment by Zedd7** [comment]
Ticket closed : the bug is caused by an incompatibility with the plugin HorseTpWithMe
